### ISSUE TITLE
GIFs and Videos won't load, or won't load right at all.

### ISSUE THREAD

**Issue by chrdov** [vbousquet/flexdmd#23] opened 2021-04-29 14:06 UTC
FlexDMD GIFs and Videos will not load after the first time running the table, or they won't load right at all.

Attached are the GIFs I'm trying to use in question. 
![Animated_Fire_1](https://user-images.githubusercontent.com/20271526/116563774-581fa700-a8d2-11eb-9ae3-26072fc21e5e.gif)
![CrimsonHot](https://user-images.githubusercontent.com/20271526/116563775-581fa700-a8d2-11eb-955c-503a9b212273.gif)
![Fireball](https://user-images.githubusercontent.com/20271526/116563778-581fa700-a8d2-11eb-98d7-e9fb078ab7d2.gif)
![Fireball_Attract](https://user-images.githubusercontent.com/20271526/116563779-581fa700-a8d2-11eb-862b-ae05869b905a.gif)
![Hellfire_Slogan](https://user-images.githubusercontent.com/20271526/116563780-58b83d80-a8d2-11eb-8cbf-17ebf2011b3a.gif)

Whenever I use the first one in particular as a background, it just shows up as a black background and not an animated fire background.

I even tried reloading Visual Pinball X, reloading the table, and reinstalling this software.

My name on VPForums is OctoChris. I also posted this issue there: 

https://www.vpforums.org/index.php?showtopic=43569&page=32#entry476150

**Comment by vbousquet** [comment] 2021-04-29 22:50
CLosing as it is marked as not a bug, and solved in the VPForums post.

**Closed by vbousquet** 2021-04-29 22:50 UTC
